### ISSUE TITLE
Can you push code in the models\mmseg\models\sam part?

### ISSUE THREAD

**Issue by UreMine02** [DragonDescentZerotsu/SSM-SAM#1]

**Comment by DragonDescentZerotsu** [comment]
I've just uploaded the missing ones, see if it works for you

**Comment by UreMine02** [comment]
I saw your new update on github. But I didn't see any changes in
models\mmseg\models\sam part (in which include image_encoder.py,
prompt_encoder.py,...). I really want to know this part because in current
code, I don't see the part showing cross attention between Gaussian mask
and query image in the current code as well as you embed Gaussian mask.

**Comment by DragonDescentZerotsu** [comment]
See now

**Comment by UreMine02** [comment]
I saw your new update on github and it works now. I still have one more
question: did your project support prompts which are in original SAM?

**Comment by DragonDescentZerotsu** [comment]
Yes there are prompts but automatically done by randomly choosing a point on the ground truth area (mask area), you can modify the code to make it interactive

**Comment by UreMine02** [comment]
Thank you for being so helpful.
